image: alpine:3.7

pages:
  stage: deploy
  script:
    - apk update
    - apk add git python3 py3-lxml
    - python3 -m pip --version
    - "python3 -m pip install git+https://github.com/regebro/hovercraft@\
       481f053cd5e22efda51c7ae290f2298d552dbe39"
    - hovercraft --version
    - hovercraft talk.txt public
    - ls -l public/index.html
    - sha256sum public/index.html
  artifacts: { paths: [public,] }
